"""
GRD Chat — Interactive inference for the Geometric Reservoir Delta model.
Usage:
    python ultimate/grd_chat.py --model ultimate/grd_35m_v1.pt --size 35m
    python ultimate/grd_chat.py --model ultimate/grd_35m_instruct.pt --size 35m --instruct
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import torch
import torch.nn.functional as F
import argparse

from ultimate.grd import GRDConfig, GRDModel

# ── Size presets (must match what was used during training) ───────────────────
CONFIGS = {
    "10m": GRDConfig(d_model=256, n_layers=4, n_heads=4, d_k=64, d_v=64, d_ff=512),
    "35m": GRDConfig(d_model=384, n_layers=6, n_heads=6, d_k=64, d_v=64, d_ff=1024),
    "120m": GRDConfig(d_model=768, n_layers=12, n_heads=12, d_k=64, d_v=64, d_ff=2048),
}

def load_model(model_path, size, device):
    cfg   = CONFIGS[size]
    model = GRDModel(cfg).to(device)
    sd    = torch.load(model_path, map_location=device, weights_only=True)
    model.load_state_dict(sd)
    model.eval()
    params  = sum(p.numel() for p in model.parameters())
    size_mb = os.path.getsize(model_path) / 1e6
    print(f"[*] Loaded GRD {size.upper()} ({params:,} params | {size_mb:.1f} MB)")
    return model


@torch.no_grad()
def generate(model, prompt_text: str, max_new_bytes: int, temp: float,
             device, prior_states=None):
    """
    Run auto-regressive byte-level generation.
    Returns (response_str, final_states) so the caller can carry
    state across conversation turns.
    """
    temp = max(temp, 1e-5)
    prompt_bytes  = prompt_text.encode("utf-8", errors="replace")
    prompt_tensor = torch.tensor(
        list(prompt_bytes), dtype=torch.long, device=device
    ).unsqueeze(0)  # [1, T]

    # ── Prefill: run the full prompt through the model ────────────────────
    logits, states = model(prompt_tensor, prior_states)

    # ── Sample + print first generated byte ──────────────────────────────
    next_byte = torch.multinomial(
        F.softmax(logits[:, -1] / temp, dim=-1), num_samples=1
    )
    b = next_byte.item()
    try:
        sys.stdout.write(bytes([b]).decode("utf-8"))
    except UnicodeDecodeError:
        sys.stdout.write(".")
    sys.stdout.flush()

    # ── Auto-regressive generation: one byte at a time, O(1) per step ────
    for _ in range(max_new_bytes - 1):
        logits, states = model(next_byte, states)
        next_byte = torch.multinomial(
            F.softmax(logits[:, -1] / temp, dim=-1), num_samples=1
        )
        b = next_byte.item()
        try:
            sys.stdout.write(bytes([b]).decode("utf-8"))
        except UnicodeDecodeError:
            sys.stdout.write(".")
        sys.stdout.flush()

    return states   # return so caller can continue the conversation


def main():
    parser = argparse.ArgumentParser(description="GRD Interactive Chat")
    parser.add_argument("--model",   default="ultimate/grd_35m_v1.pt")
    parser.add_argument("--size",    default="35m", choices=["10m", "35m", "120m"])
    parser.add_argument("--max_new", type=int,   default=200,
                        help="Max bytes to generate per response")
    parser.add_argument("--temp",    type=float, default=0.8,
                        help="Sampling temperature (0.5=focused, 1.0=creative)")
    parser.add_argument("--instruct", action="store_true",
                        help="Use User:/GRD: format (required for instruct checkpoints)")
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")
    model = load_model(args.model, args.size, device)

    print()
    print("=" * 60)
    print("   GRD  —  Geometric Reservoir Delta  —  Chat")
    print("=" * 60)
    if args.instruct:
        print("Mode : INSTRUCT  (answers questions, follows instructions)")
    else:
        print("Mode : BASE  (raw text continuation from your prompt)")
    print("Tip  : type 'reset' to clear conversation memory.")
    print("Tip  : use --temp 0.5 for more focused answers.\n")

    conv_states = None   # recurrent state carried across all turns

    while True:
        try:
            prompt = input("You  > ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nBye.")
            break

        if not prompt:
            continue
        if prompt.lower() in ("quit", "exit", "q"):
            print("Bye.")
            break
        if prompt.lower() == "reset":
            conv_states = None
            print("[*] Conversation memory cleared.\n")
            continue

        # Wrap in instruction template if requested
        if args.instruct:
            formatted = f"User: {prompt}\nGRD: "
        else:
            formatted = prompt

        print("GRD  > ", end="", flush=True)
        conv_states = generate(
            model, formatted, args.max_new, args.temp, device,
            prior_states=conv_states
        )
        print("\n")


if __name__ == "__main__":
    main()

