import torch
import os
import sys
import argparse

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from hgdm_omega import OmegaGDM, OmegaConfig

def chat():
    parser = argparse.ArgumentParser(description="Chat with DPO-aligned OmegaGDM")
    parser.add_argument("--ckpt", type=str, default="omega_slm_dpo_latest.pt", help="Checkpoint path")
    parser.add_argument("--temp", type=float, default=0.7, help="Generation temperature")
    parser.add_argument("--max-len", type=int, default=256, help="Max bytes to generate")
    args = parser.parse_args()

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"[System] Loading {args.ckpt} on {device}...")

    omega_cfg = OmegaConfig(
        d_byte=256, catcher_layers=2, renderer_layers=2,
        d_model=768, core_layers=12, n_heads=12,
        d_k=64, d_v=64, d_ff=3072,
        decimation_rate=8, max_position_embeddings=2048,
        vocab_size=256, use_state_fusion=False
    )
    
    model = OmegaGDM(omega_cfg, force_sequential=False).to(device)
    
    if not os.path.exists(args.ckpt):
        print(f"[ERROR] Checkpoint {args.ckpt} not found!")
        sys.exit(1)
        
    ckpt = torch.load(args.ckpt, map_location=device)
    # Handle both 'model' and 'model_state_dict' keys
    state_dict = ckpt.get('model', ckpt.get('model_state_dict'))
    model.load_state_dict(state_dict)
    model.eval()
    print("[System] Model loaded and ready! (Type 'quit' to exit)")
    print("=====================================================")

    while True:
        try:
            user_input = input("\nYou: ")
            if user_input.lower() in ['quit', 'exit']:
                break
                
            # Format as ChatML
            prompt_str = f"<|im_start|>user\n{user_input}<|im_end|>\n<|im_start|>assistant\n"
            prompt_bytes = list(prompt_str.encode('utf-8', errors='replace'))
            prompt_tensor = torch.tensor([prompt_bytes], dtype=torch.long, device=device)
            
            # Generate (Autoregressive byte-level)
            with torch.no_grad():
                generated = model.generate(prompt_tensor, max_new_bytes=args.max_len, temp=args.temp)
            
            # Decode only the newly generated bytes
            new_bytes = generated[0, len(prompt_bytes):].tolist()
            decoded = bytes(new_bytes).decode('utf-8', errors='replace')
            
            # Stop generation visually at the IM_END tag
            if "<|im_end|>" in decoded:
                decoded = decoded.split("<|im_end|>")[0]
                
            print(f"Assistant: {decoded}")
            
        except KeyboardInterrupt:
            break

if __name__ == "__main__":
    chat()
